-- 轻课堂 RAG 知识库基础表
-- 推荐上线方式：alembic upgrade head
-- 本脚本用于无 Alembic 环境下的人工部署，重复执行安全。

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS knowledge_base (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    embedding_model VARCHAR(100) NOT NULL DEFAULT 'bge-base-zh-v1.5',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_knowledge_base_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX IF NOT EXISTS ix_knowledge_base_tenant_id ON knowledge_base (tenant_id);
CREATE INDEX IF NOT EXISTS ix_knowledge_base_enabled ON knowledge_base (enabled);

CREATE TABLE IF NOT EXISTS knowledge_document (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_base(id),
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL DEFAULT 'text/plain',
    content_hash VARCHAR(64) NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'queued',
    chunk_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_by INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_knowledge_document_hash UNIQUE (knowledge_base_id, content_hash)
);

CREATE INDEX IF NOT EXISTS ix_knowledge_document_tenant_id ON knowledge_document (tenant_id);
CREATE INDEX IF NOT EXISTS ix_knowledge_document_base_id ON knowledge_document (knowledge_base_id);
CREATE INDEX IF NOT EXISTS ix_knowledge_document_status ON knowledge_document (status);

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_base(id),
    document_id INTEGER NOT NULL REFERENCES knowledge_document(id),
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    source_locator VARCHAR(255) NOT NULL DEFAULT '',
    embedding vector(768),
    embedding_model VARCHAR(100) NOT NULL DEFAULT 'bge-base-zh-v1.5',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_knowledge_chunk_tenant_base
    ON knowledge_chunk (tenant_id, knowledge_base_id);
CREATE INDEX IF NOT EXISTS ix_knowledge_chunk_document
    ON knowledge_chunk (document_id);
CREATE INDEX IF NOT EXISTS ix_knowledge_chunk_embedding_hnsw
    ON knowledge_chunk USING hnsw (embedding vector_cosine_ops);
