-- 大模型服务商（租户级）
-- 上线初始化：可在 alembic upgrade head 之后再执行（全部 IF NOT EXISTS / 幂等插入）
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/schema/ai_provider.sql

CREATE TABLE IF NOT EXISTS ai_provider (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    name varchar(80) NOT NULL,
    provider_type varchar(32) NOT NULL DEFAULT 'OPENAI',
    base_url varchar(300) NOT NULL,
    api_key varchar(512) NOT NULL DEFAULT '',
    chat_model varchar(120),
    vision_model varchar(120),
    image_model varchar(120),
    video_model varchar(120),
    audio_model varchar(120),
    timeout_seconds integer NOT NULL DEFAULT 120,
    is_default boolean NOT NULL DEFAULT false,
    status integer NOT NULL DEFAULT 1,
    sort integer NOT NULL DEFAULT 0,
    remark varchar(200),
    last_test_status integer,
    last_test_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_ai_provider_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX IF NOT EXISTS ix_ai_provider_tenant_id ON ai_provider (tenant_id);
CREATE INDEX IF NOT EXISTS ix_ai_provider_provider_type ON ai_provider (provider_type);
CREATE INDEX IF NOT EXISTS ix_ai_provider_is_default ON ai_provider (is_default);
CREATE INDEX IF NOT EXISTS ix_ai_provider_status ON ai_provider (status);

COMMENT ON TABLE ai_provider IS '大模型服务商（按学校隔离，密钥只存不回显）';

INSERT INTO permission (code, name, module, sort)
VALUES
  ('ai_provider:view', '查看大模型服务商', '服务商管理', 90),
  ('ai_provider:manage', '配置大模型服务商', '服务商管理', 91)
ON CONFLICT (code) DO NOTHING;

INSERT INTO menu (key, name, path, icon, sort, enabled, roles_csv, required_capability, group_key, group_title, group_icon, group_sort)
VALUES (
  'ai-providers',
  '服务商管理',
  '/ai-providers',
  'cloud',
  15,
  TRUE,
  'director',
  NULL,
  'school-affairs',
  '学籍教务',
  'school',
  20
)
ON CONFLICT (key) DO NOTHING;

INSERT INTO menu_permission (menu_key, permission_id)
SELECT 'ai-providers', p.id
FROM permission p
WHERE p.code IN ('ai_provider:view', 'ai_provider:manage')
  AND NOT EXISTS (
    SELECT 1 FROM menu_permission mp
    WHERE mp.menu_key = 'ai-providers' AND mp.permission_id = p.id
  );

INSERT INTO rbac_role_permission_template (role_code, permission_code)
VALUES
  ('school_admin', 'ai_provider:view'),
  ('school_admin', 'ai_provider:manage')
ON CONFLICT DO NOTHING;
