"""initial schema

Revision ID: 6da9d303d39b
Revises: 
Create Date: 2026-08-24 01:50:54.978018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6da9d303d39b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answerscore',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('ai_score', sa.Numeric(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(), nullable=True),
    sa.Column('ai_comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('grading_mode', sa.Enum('manual', 'ocr', 'ai_pre', name='gradingmode'), nullable=False),
    sa.Column('confirm_status', sa.Enum('pending', 'confirmed', 'changed', name='confirmstatus'), nullable=False),
    sa.Column('grader_id', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_answerscore_sub_ques'),
    comment='每题得分'
    )
    op.create_index(op.f('ix_answerscore_question_id'), 'answerscore', ['question_id'], unique=False)
    op.create_index(op.f('ix_answerscore_submission_id'), 'answerscore', ['submission_id'], unique=False)
    op.create_index(op.f('ix_answerscore_tenant_id'), 'answerscore', ['tenant_id'], unique=False)
    op.create_table('auditlog',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='审计日志'
    )
    op.create_index(op.f('ix_auditlog_created_at'), 'auditlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditlog_tenant_id'), 'auditlog', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.create_table('checkinrecord',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('batch', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('method', sa.Enum('scan', 'manual', 'phone', name='checkinmethod'), nullable=False),
    sa.Column('verify_fields', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='报到记录'
    )
    op.create_index(op.f('ix_checkinrecord_student_id'), 'checkinrecord', ['student_id'], unique=False)
    op.create_index(op.f('ix_checkinrecord_tenant_id'), 'checkinrecord', ['tenant_id'], unique=False)
    op.create_table('class',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('head_teacher_id', sa.Integer(), nullable=True),
    sa.Column('deputy_head_teacher_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='班级'
    )
    op.create_index(op.f('ix_class_grade_id'), 'class', ['grade_id'], unique=False)
    op.create_index(op.f('ix_class_tenant_id'), 'class', ['tenant_id'], unique=False)
    op.create_table('enrollmentbatch',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('importing', 'partial', 'finished', name='enrollmentstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='新生导入批次'
    )
    op.create_index(op.f('ix_enrollmentbatch_tenant_id'), 'enrollmentbatch', ['tenant_id'], unique=False)
    op.create_table('exam',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('exam_type', sa.Enum('weekly', 'monthly', 'midterm', 'final', 'mock', name='examtype'), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('preparing', 'ongoing', 'finished', 'archived', name='examstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='考试'
    )
    op.create_index(op.f('ix_exam_tenant_id'), 'exam', ['tenant_id'], unique=False)
    op.create_table('examtrend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('exam_nature', sa.Enum('gaokao', 'mock', 'monthly', 'midterm', 'final', 'weekly', name='examnature'), nullable=False),
    sa.Column('appear_count', sa.Integer(), nullable=False),
    sa.Column('score_weight', sa.Numeric(), nullable=False),
    sa.Column('trend_score', sa.Numeric(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='考点趋势'
    )
    op.create_index(op.f('ix_examtrend_knowledge_point_id'), 'examtrend', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_examtrend_subject_id'), 'examtrend', ['subject_id'], unique=False)
    op.create_table('grade',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='年级'
    )
    op.create_index(op.f('ix_grade_tenant_id'), 'grade', ['tenant_id'], unique=False)
    op.create_table('hottopic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sa.Enum('politics', 'tech', 'livelihood', 'culture', 'sports', 'finance', name='topiccategory'), nullable=False),
    sa.Column('heat_index', sa.Integer(), nullable=False),
    sa.Column('heat_date', sa.Date(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('related_subjects', sa.JSON(), nullable=True),
    sa.Column('trend_direction', sa.Enum('up', 'stable', 'down', name='trenddirection'), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='社会热点'
    )
    op.create_table('knowledgepoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='知识点'
    )
    op.create_index(op.f('ix_knowledgepoint_code'), 'knowledgepoint', ['code'], unique=False)
    op.create_index(op.f('ix_knowledgepoint_parent_id'), 'knowledgepoint', ['parent_id'], unique=False)
    op.create_index(op.f('ix_knowledgepoint_subject_id'), 'knowledgepoint', ['subject_id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单'
    )
    op.create_index(op.f('ix_menu_parent_id'), 'menu', ['parent_id'], unique=False)
    op.create_table('paper',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('total_score', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('building', 'finalized', 'grading', 'published', name='paperstatus'), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('exam_nature', sa.Enum('gaokao', 'mock', 'monthly', 'midterm', 'final', 'weekly', name='examnature'), nullable=True),
    sa.Column('source_type', sa.Enum('real', 'mock', 'tutoring', 'web', 'self', name='sourcetype'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='试卷'
    )
    op.create_index(op.f('ix_paper_exam_id'), 'paper', ['exam_id'], unique=False)
    op.create_index(op.f('ix_paper_grade_id'), 'paper', ['grade_id'], unique=False)
    op.create_index(op.f('ix_paper_subject_id'), 'paper', ['subject_id'], unique=False)
    op.create_index(op.f('ix_paper_tenant_id'), 'paper', ['tenant_id'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='权限点'
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_module'), 'permission', ['module'], unique=False)
    op.create_table('practicequestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_sheet_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('basic', 'mid', 'advanced', name='difficultylevel'), nullable=False),
    sa.Column('origin_question_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('earned_score', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='巩固卷题目'
    )
    op.create_index(op.f('ix_practicequestion_practice_sheet_id'), 'practicequestion', ['practice_sheet_id'], unique=False)
    op.create_table('practicesheet',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_paper_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('generated', 'reviewed', 'printed', 'returned', name='practicestatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='巩固卷'
    )
    op.create_index(op.f('ix_practicesheet_student_id'), 'practicesheet', ['student_id'], unique=False)
    op.create_index(op.f('ix_practicesheet_tenant_id'), 'practicesheet', ['tenant_id'], unique=False)
    op.create_table('predictionfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_item_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('actual_appeared', sa.Boolean(), nullable=False),
    sa.Column('actual_weight', sa.Numeric(), nullable=False),
    sa.Column('feedback_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='押题效果反馈'
    )
    op.create_index(op.f('ix_predictionfeedback_exam_id'), 'predictionfeedback', ['exam_id'], unique=False)
    op.create_index(op.f('ix_predictionfeedback_prediction_item_id'), 'predictionfeedback', ['prediction_item_id'], unique=False)
    op.create_table('predictionitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_task_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.Enum('single', 'multi', 'fill', 'short_answer', 'calc', 'essay', name='questiontype'), nullable=False),
    sa.Column('difficulty', sa.Enum('basic', 'mid', 'advanced', name='difficultylevel'), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('pending', 'adopted', 'rejected', name='predictionitemstatus'), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('generated_question_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='押题结果明细'
    )
    op.create_index(op.f('ix_predictionitem_prediction_task_id'), 'predictionitem', ['prediction_task_id'], unique=False)
    op.create_table('predictiontask',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sa.Enum('queued', 'generating', 'generated', 'reviewed', 'published', 'discarded', name='predictiontaskstatus'), nullable=False),
    sa.Column('confidence_avg', sa.Numeric(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='押题任务'
    )
    op.create_index(op.f('ix_predictiontask_exam_id'), 'predictiontask', ['exam_id'], unique=False)
    op.create_index(op.f('ix_predictiontask_subject_id'), 'predictiontask', ['subject_id'], unique=False)
    op.create_index(op.f('ix_predictiontask_tenant_id'), 'predictiontask', ['tenant_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('basic', 'mid', 'advanced', name='difficultylevel'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer_region', sa.JSON(), nullable=True),
    sa.Column('question_type', sa.Enum('single', 'multi', 'fill', 'short_answer', 'calc', 'essay', name='questiontype'), nullable=True),
    sa.Column('source_type', sa.Enum('real', 'mock', 'tutoring', 'web', 'self', name='sourcetype'), nullable=True),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='题目'
    )
    op.create_index(op.f('ix_question_knowledge_point_id'), 'question', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_question_paper_id'), 'question', ['paper_id'], unique=False)
    op.create_table('questionbank',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('basic', 'mid', 'advanced', name='difficultylevel'), nullable=False),
    sa.Column('question_type', sa.Enum('single', 'multi', 'fill', 'short_answer', 'calc', 'essay', name='questiontype'), nullable=False),
    sa.Column('source_type', sa.Enum('real', 'mock', 'tutoring', 'web', 'self', name='sourcetype'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='题目库'
    )
    op.create_index(op.f('ix_questionbank_subject_id'), 'questionbank', ['subject_id'], unique=False)
    op.create_index(op.f('ix_questionbank_tenant_id'), 'questionbank', ['tenant_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='角色'
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=True)
    op.create_table('rolemenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='角色-菜单关联'
    )
    op.create_index(op.f('ix_rolemenu_menu_id'), 'rolemenu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_rolemenu_role_id'), 'rolemenu', ['role_id'], unique=False)
    op.create_table('rolepermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='角色-权限关联'
    )
    op.create_index(op.f('ix_rolepermission_permission_id'), 'rolepermission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rolepermission_role_id'), 'rolepermission', ['role_id'], unique=False)
    op.create_table('scanbatch',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'split', 'assigned', 'confirmed', name='scanbatchstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='扫描批次'
    )
    op.create_index(op.f('ix_scanbatch_paper_id'), 'scanbatch', ['paper_id'], unique=False)
    op.create_index(op.f('ix_scanbatch_tenant_id'), 'scanbatch', ['tenant_id'], unique=False)
    op.create_table('scanpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('cos_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='扫描页'
    )
    op.create_index(op.f('ix_scanpage_batch_id'), 'scanpage', ['batch_id'], unique=False)
    op.create_index(op.f('ix_scanpage_student_id'), 'scanpage', ['student_id'], unique=False)
    op.create_table('schedule',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='课表项',
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_schedule_class_id'), 'schedule', ['class_id'], unique=False)
    op.create_index(op.f('ix_schedule_tenant_id'), 'schedule', ['tenant_id'], unique=False)
    op.create_table('seatarrangement',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Enum('height', 'grade', 'gender', 'snake', 'manual', name='seatrule'), nullable=False),
    sa.Column('student_map', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='seatstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='排座位'
    )
    op.create_index(op.f('ix_seatarrangement_class_id'), 'seatarrangement', ['class_id'], unique=False)
    op.create_index(op.f('ix_seatarrangement_tenant_id'), 'seatarrangement', ['tenant_id'], unique=False)
    op.create_table('student',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('id_card', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('parent_phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('student_no', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('roster_order', sa.Integer(), nullable=False),
    sa.Column('check_in_status', sa.Enum('none', 'checked', 'hand_confirmed', 'contacting', name='checkinstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('studying', 'leave', 'transferred', name='studentstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='学生'
    )
    op.create_index(op.f('ix_student_class_id'), 'student', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_gender'), 'student', ['gender'], unique=False)
    op.create_index(op.f('ix_student_student_no'), 'student', ['student_no'], unique=False)
    op.create_index(op.f('ix_student_tenant_id'), 'student', ['tenant_id'], unique=False)
    op.create_table('studentprofile',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('weak', 'mid', 'excellent', name='profiletier'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='学生画像'
    )
    op.create_index(op.f('ix_studentprofile_knowledge_point_id'), 'studentprofile', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_studentprofile_student_id'), 'studentprofile', ['student_id'], unique=False)
    op.create_index(op.f('ix_studentprofile_tenant_id'), 'studentprofile', ['tenant_id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='学科字典'
    )
    op.create_table('submission',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('absent', 'scanned', 'grading', 'graded', 'published', name='submissionstatus'), nullable=False),
    sa.Column('total_score', sa.Numeric(), nullable=False),
    sa.Column('graded_by', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'student_id', name='uq_submission_paper_student'),
    comment='作答记录'
    )
    op.create_index(op.f('ix_submission_paper_id'), 'submission', ['paper_id'], unique=False)
    op.create_index(op.f('ix_submission_student_id'), 'submission', ['student_id'], unique=False)
    op.create_index(op.f('ix_submission_tenant_id'), 'submission', ['tenant_id'], unique=False)
    op.create_table('teacherstyle',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('preferred_kp', sa.JSON(), nullable=True),
    sa.Column('difficulty_dist', sa.JSON(), nullable=True),
    sa.Column('type_dist', sa.JSON(), nullable=True),
    sa.Column('source_preference', sa.JSON(), nullable=True),
    sa.Column('style_vector', sa.JSON(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='老师风格画像'
    )
    op.create_index(op.f('ix_teacherstyle_subject_id'), 'teacherstyle', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacherstyle_teacher_id'), 'teacherstyle', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacherstyle_tenant_id'), 'teacherstyle', ['tenant_id'], unique=False)
    op.create_table('teachingassignment',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='任教关系'
    )
    op.create_index(op.f('ix_teachingassignment_class_id'), 'teachingassignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_teachingassignment_subject_id'), 'teachingassignment', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teachingassignment_teacher_id'), 'teachingassignment', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teachingassignment_tenant_id'), 'teachingassignment', ['tenant_id'], unique=False)
    op.create_table('teachingplan',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('weekly', 'unit', 'pre_exam', 'suggestion', name='plantype'), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'referred', 'edited', name='planstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='AI教学计划'
    )
    op.create_index(op.f('ix_teachingplan_class_id'), 'teachingplan', ['class_id'], unique=False)
    op.create_index(op.f('ix_teachingplan_subject_id'), 'teachingplan', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teachingplan_tenant_id'), 'teachingplan', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sa.Enum('personal', 'org', name='tenanttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='租户(学校)'
    )
    op.create_index(op.f('ix_tenant_code'), 'tenant', ['code'], unique=True)
    op.create_table('tenantconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('config_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='租户个性化配置'
    )
    op.create_index(op.f('ix_tenantconfig_tenant_id'), 'tenantconfig', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('director', 'teacher', name='baseuserrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='用户'
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('userrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='用户-角色关联'
    )
    op.create_index(op.f('ix_userrole_role_id'), 'userrole', ['role_id'], unique=False)
    op.create_index(op.f('ix_userrole_user_id'), 'userrole', ['user_id'], unique=False)
    op.create_table('wrongquestion',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('source_paper_id', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(), nullable=False),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='错题集'
    )
    op.create_index(op.f('ix_wrongquestion_question_id'), 'wrongquestion', ['question_id'], unique=False)
    op.create_index(op.f('ix_wrongquestion_student_id'), 'wrongquestion', ['student_id'], unique=False)
    op.create_index(op.f('ix_wrongquestion_tenant_id'), 'wrongquestion', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wrongquestion_tenant_id'), table_name='wrongquestion')
    op.drop_index(op.f('ix_wrongquestion_student_id'), table_name='wrongquestion')
    op.drop_index(op.f('ix_wrongquestion_question_id'), table_name='wrongquestion')
    op.drop_table('wrongquestion')
    op.drop_index(op.f('ix_userrole_user_id'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_role_id'), table_name='userrole')
    op.drop_table('userrole')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tenantconfig_tenant_id'), table_name='tenantconfig')
    op.drop_table('tenantconfig')
    op.drop_index(op.f('ix_tenant_code'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_teachingplan_tenant_id'), table_name='teachingplan')
    op.drop_index(op.f('ix_teachingplan_subject_id'), table_name='teachingplan')
    op.drop_index(op.f('ix_teachingplan_class_id'), table_name='teachingplan')
    op.drop_table('teachingplan')
    op.drop_index(op.f('ix_teachingassignment_tenant_id'), table_name='teachingassignment')
    op.drop_index(op.f('ix_teachingassignment_teacher_id'), table_name='teachingassignment')
    op.drop_index(op.f('ix_teachingassignment_subject_id'), table_name='teachingassignment')
    op.drop_index(op.f('ix_teachingassignment_class_id'), table_name='teachingassignment')
    op.drop_table('teachingassignment')
    op.drop_index(op.f('ix_teacherstyle_tenant_id'), table_name='teacherstyle')
    op.drop_index(op.f('ix_teacherstyle_teacher_id'), table_name='teacherstyle')
    op.drop_index(op.f('ix_teacherstyle_subject_id'), table_name='teacherstyle')
    op.drop_table('teacherstyle')
    op.drop_index(op.f('ix_submission_tenant_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_student_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_paper_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_table('subject')
    op.drop_index(op.f('ix_studentprofile_tenant_id'), table_name='studentprofile')
    op.drop_index(op.f('ix_studentprofile_student_id'), table_name='studentprofile')
    op.drop_index(op.f('ix_studentprofile_knowledge_point_id'), table_name='studentprofile')
    op.drop_table('studentprofile')
    op.drop_index(op.f('ix_student_tenant_id'), table_name='student')
    op.drop_index(op.f('ix_student_student_no'), table_name='student')
    op.drop_index(op.f('ix_student_gender'), table_name='student')
    op.drop_index(op.f('ix_student_class_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_seatarrangement_tenant_id'), table_name='seatarrangement')
    op.drop_index(op.f('ix_seatarrangement_class_id'), table_name='seatarrangement')
    op.drop_table('seatarrangement')
    op.drop_index(op.f('ix_schedule_tenant_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_class_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_scanpage_student_id'), table_name='scanpage')
    op.drop_index(op.f('ix_scanpage_batch_id'), table_name='scanpage')
    op.drop_table('scanpage')
    op.drop_index(op.f('ix_scanbatch_tenant_id'), table_name='scanbatch')
    op.drop_index(op.f('ix_scanbatch_paper_id'), table_name='scanbatch')
    op.drop_table('scanbatch')
    op.drop_index(op.f('ix_rolepermission_role_id'), table_name='rolepermission')
    op.drop_index(op.f('ix_rolepermission_permission_id'), table_name='rolepermission')
    op.drop_table('rolepermission')
    op.drop_index(op.f('ix_rolemenu_role_id'), table_name='rolemenu')
    op.drop_index(op.f('ix_rolemenu_menu_id'), table_name='rolemenu')
    op.drop_table('rolemenu')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_questionbank_tenant_id'), table_name='questionbank')
    op.drop_index(op.f('ix_questionbank_subject_id'), table_name='questionbank')
    op.drop_table('questionbank')
    op.drop_index(op.f('ix_question_paper_id'), table_name='question')
    op.drop_index(op.f('ix_question_knowledge_point_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_predictiontask_tenant_id'), table_name='predictiontask')
    op.drop_index(op.f('ix_predictiontask_subject_id'), table_name='predictiontask')
    op.drop_index(op.f('ix_predictiontask_exam_id'), table_name='predictiontask')
    op.drop_table('predictiontask')
    op.drop_index(op.f('ix_predictionitem_prediction_task_id'), table_name='predictionitem')
    op.drop_table('predictionitem')
    op.drop_index(op.f('ix_predictionfeedback_prediction_item_id'), table_name='predictionfeedback')
    op.drop_index(op.f('ix_predictionfeedback_exam_id'), table_name='predictionfeedback')
    op.drop_table('predictionfeedback')
    op.drop_index(op.f('ix_practicesheet_tenant_id'), table_name='practicesheet')
    op.drop_index(op.f('ix_practicesheet_student_id'), table_name='practicesheet')
    op.drop_table('practicesheet')
    op.drop_index(op.f('ix_practicequestion_practice_sheet_id'), table_name='practicequestion')
    op.drop_table('practicequestion')
    op.drop_index(op.f('ix_permission_module'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_paper_tenant_id'), table_name='paper')
    op.drop_index(op.f('ix_paper_subject_id'), table_name='paper')
    op.drop_index(op.f('ix_paper_grade_id'), table_name='paper')
    op.drop_index(op.f('ix_paper_exam_id'), table_name='paper')
    op.drop_table('paper')
    op.drop_index(op.f('ix_menu_parent_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_knowledgepoint_subject_id'), table_name='knowledgepoint')
    op.drop_index(op.f('ix_knowledgepoint_parent_id'), table_name='knowledgepoint')
    op.drop_index(op.f('ix_knowledgepoint_code'), table_name='knowledgepoint')
    op.drop_table('knowledgepoint')
    op.drop_table('hottopic')
    op.drop_index(op.f('ix_grade_tenant_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_examtrend_subject_id'), table_name='examtrend')
    op.drop_index(op.f('ix_examtrend_knowledge_point_id'), table_name='examtrend')
    op.drop_table('examtrend')
    op.drop_index(op.f('ix_exam_tenant_id'), table_name='exam')
    op.drop_table('exam')
    op.drop_index(op.f('ix_enrollmentbatch_tenant_id'), table_name='enrollmentbatch')
    op.drop_table('enrollmentbatch')
    op.drop_index(op.f('ix_class_tenant_id'), table_name='class')
    op.drop_index(op.f('ix_class_grade_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_checkinrecord_tenant_id'), table_name='checkinrecord')
    op.drop_index(op.f('ix_checkinrecord_student_id'), table_name='checkinrecord')
    op.drop_table('checkinrecord')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_tenant_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_created_at'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_answerscore_tenant_id'), table_name='answerscore')
    op.drop_index(op.f('ix_answerscore_submission_id'), table_name='answerscore')
    op.drop_index(op.f('ix_answerscore_question_id'), table_name='answerscore')
    op.drop_table('answerscore')
    # ### end Alembic commands ###
